### ISSUE TITLE
No sound on any title

### ISSUE THREAD

**Issue by Davometric** [dmcoles/EstyJs#4]
Tried toggling the sound option. No sound. Tried both chrome and edge and many different games. Am I missing something?

**Comment by dmcoles** [comment]
This was developed some years ago and I think the audio api in the browsers has changed since then. I will try to find some time to see if it can be updated.

**Comment by Davometric** [comment]
Awesome! It's actually a solid emulator, even works natively with my DS5 controller!

**Comment by dmcoles** [comment]
ok i have a quick workaround for now that starts the emulator with the sound disabled. Browsers don't allow sites to simply start playing audio without a user interaction anymore. There is still a problem with the audio code using a deprecated function that will no doubt stop working at some point but for now it is working again.

**Comment by Davometric** [comment]
Sweet! Just tested on the latest version of chrome and everything is working great! Thanks for your hard work!
