### ISSUE TITLE
Interlaced screen

### ISSUE THREAD

**Issue by kaiec** [dmcoles/EstyJs#5]
Hey there,

awesome piece of code! I am just wondering why the image looks like every other line is not drawn, kind of like an interlaced mode. Is this a bug?

![image](https://github.com/user-attachments/assets/ce40fc35-08a9-46de-bad3-b94ab6ff9949)

**Comment by kaiec** [comment]
Fixed it here and made it configurable with setRowSkip(false), which draws all lines.

[https://github.com/kaiec/EstyJs/](https://github.com/kaiec/EstyJs/)

**Comment by dmcoles** [comment]
not exactly a bug as it was intentional but nice that you have given the option of turning it off.

**Comment by kaiec** [comment]
I can create a pull request if you want to merge it into your code.
