### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by kaiec** [dmcoles/EstyJs#6]
I just noticed that you do not have a license specified in your repo. Would you be willing to add an Open Source License such as MIT (or whatever you prefer)? As it stands right now, modifications and further development of the code would actually not be allowed, which would be really sad.

**Comment by kaiec** [comment]
Great, thank you!

**Comment by dmcoles** [comment]
this uses portions of code from the SAE Amiga emulator which is GPL, so i have added the relevant GPL license information.

**Comment by kaiec** [comment]
Awesome, thanks a lot!

There is actually a standardized way to add the license in GitHub: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository 

You just have to add a new file via the  GitHub page, call it LICENSE or LICENSE.md and there will be a link to choose a template where you can then select GPL.   This way the license is parsed by GitHub and shown to everyone on the right side of your repo.

**Comment by dmcoles** [comment]
thanks for the tip, i have now also added that file
